spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/judgementsystem?&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 911438
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8081

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
